import type { NextPage } from 'next';
import Head from 'next/head';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const connectWallet = () => {
    // connectWallet işlevi buraya eklenebilir
  };

  const signInWithEmail = () => {
    // signInWithEmail işlevi buraya eklenebilir
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
        <script src="script.js" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <div className="container">
          <img src="img/logo.svg" alt="FairShare Logo" className="logo" />
          <p className="description">Sign in to support those in need or get the support you need.</p>
          <button className="btn" onClick={connectWallet}>Sign in with WorldID</button>
          <button className="btn" onClick={signInWithEmail}>Sign in with Mail</button>
          <p className="footer-note">In order to receive funds you must sign in with WorldID.</p>
        </div>
      </main>
    </div>
  );
};

export default Home;
